import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

const dummyStaffMembers = [
  {
    id: "Musa-ahmad",
    name: "Hasan Ahmad",
    role: "CEO & Founder",
    bio: "Visionary leader with 10+ years of experience in software development and business strategy. Passionate about leveraging technology to solve complex problems.",
    avatar: "/avatars/hasan.jpg",
    email: "hasan@quantumstack.tech",
    linkedin: "https://linkedin.com/in/hasanahmad",
    twitter: "https://twitter.com/hasanahmad",
    github: "https://github.com/hasanahmad",
    skills: ["Leadership", "Strategy", "Full-Stack Development", "AI/ML"],
  },
  {
    id: "amina-yusuf",
    name: "Amina Yusuf",
    role: "CTO",
    bio: "Expert in cloud architecture and distributed systems. Leads the technical vision and ensures we stay ahead of the technology curve.",
    avatar: "/avatars/amina.jpg",
    email: "amina@quantumstack.tech",
    linkedin: "https://linkedin.com/in/aminayusuf",
    github: "https://github.com/aminayusuf",
    skills: ["Cloud Architecture", "DevOps", "System Design", "Security"],
  },
  {
    id: "david-okonkwo",
    name: "David Okonkwo",
    role: "Lead AI Engineer",
    bio: "Machine learning specialist with a focus on natural language processing and computer vision. Building the future of intelligent systems.",
    avatar: "/avatars/david.jpg",
    email: "david@quantumstack.tech",
    linkedin: "https://linkedin.com/in/davidokonkwo",
    github: "https://github.com/davidokonkwo",
    skills: ["Machine Learning", "NLP", "Computer Vision", "Python"],
  },
  {
    id: "fatima-bello",
    name: "Fatima Bello",
    role: "Senior Full-Stack Developer",
    bio: "Creative developer who bridges design and engineering. Specializes in building performant and beautiful web applications.",
    avatar: "/avatars/fatima.jpg",
    email: "fatima@quantumstack.tech",
    twitter: "https://twitter.com/fatimabello",
    github: "https://github.com/fatimabello",
    skills: ["React", "Next.js", "Node.js", "TypeScript"],
  },
  {
    id: "chukwu-emeka",
    name: "Chukwu Emeka",
    role: "Backend Engineer",
    bio: "Database expert and API architect. Ensures our systems are robust, scalable, and lightning fast.",
    avatar: "/avatars/chukwu.jpg",
    email: "chukwu@quantumstack.tech",
    github: "https://github.com/chukwuemeka",
    skills: ["Go", "PostgreSQL", "Redis", "gRPC"],
  },
  {
    id: "zainab-musa",
    name: "Zainab Musa",
    role: "UI/UX Designer",
    bio: "Human-centered designer focused on creating intuitive and delightful user experiences. Advocates for accessibility in all designs.",
    avatar: "/avatars/zainab.jpg",
    email: "zainab@quantumstack.tech",
    linkedin: "https://linkedin.com/in/zainabmusa",
    twitter: "https://twitter.com/zainabmusa",
    skills: ["UI Design", "UX Research", "Figma", "Design Systems"],
  },
];

const jobOpenings = [
  {
    id: "senior-fullstack-dev",
    title: "Senior Full-Stack Developer",
    department: "Engineering",
    location: "Lagos, Nigeria",
    type: "full-time",
    experience: "4+ years",
    description:
      "We're looking for an experienced full-stack developer to join our growing engineering team. You'll work on exciting projects ranging from enterprise solutions to cutting-edge AI applications.",
    responsibilities: [
      "Design, develop, and maintain web applications using React/Next.js and Node.js",
      "Collaborate with designers and product managers to deliver exceptional user experiences",
      "Write clean, maintainable, and well-tested code",
      "Mentor junior developers and participate in code reviews",
      "Contribute to architectural decisions and technical strategy",
    ],
    requirements: [
      "4+ years of experience in full-stack development",
      "Strong proficiency in TypeScript, React, and Node.js",
      "Experience with databases (PostgreSQL, MongoDB)",
      "Familiarity with cloud platforms (AWS, GCP, or Azure)",
      "Excellent problem-solving and communication skills",
    ],
    benefits: [
      "Competitive salary",
      "Remote work flexibility",
      "Learning & development budget",
      "Health insurance",
      "Equity options",
    ],
    salary: "₦500,000 - ₦800,000/month",
    isRemote: true,
    postedDate: "2026-01-20",
  },
  {
    id: "ai-ml-engineer",
    title: "AI/ML Engineer",
    department: "AI & Research",
    location: "Remote",
    type: "full-time",
    experience: "3+ years",
    description:
      "Join our AI team to build intelligent systems that solve real-world problems. You'll work with LLMs, computer vision, and other cutting-edge AI technologies.",
    responsibilities: [
      "Develop and deploy machine learning models for various applications",
      "Work with LLMs and implement AI-powered features",
      "Optimize model performance and inference speed",
      "Collaborate with product teams to identify AI opportunities",
      "Stay current with the latest AI research and technologies",
    ],
    requirements: [
      "3+ years of experience in ML/AI development",
      "Strong Python skills and experience with ML frameworks (PyTorch, TensorFlow)",
      "Experience with LLMs and prompt engineering",
      "Understanding of MLOps and model deployment",
      "Strong mathematical foundation in statistics and linear algebra",
    ],
    benefits: [
      "Competitive salary",
      "Fully remote position",
      "Conference & training budget",
      "Flexible working hours",
      "Latest hardware/equipment",
    ],
    salary: "₦600,000 - ₦1,000,000/month",
    isRemote: true,
    postedDate: "2026-01-18",
  },
  {
    id: "ui-ux-designer",
    title: "UI/UX Designer",
    department: "Design",
    location: "Lagos, Nigeria",
    type: "full-time",
    experience: "2+ years",
    description:
      "We're seeking a creative UI/UX designer to craft beautiful and intuitive user experiences. You'll work closely with our engineering team to bring designs to life.",
    responsibilities: [
      "Create user-centered designs for web and mobile applications",
      "Develop wireframes, prototypes, and high-fidelity mockups",
      "Conduct user research and usability testing",
      "Maintain and evolve our design system",
      "Collaborate with developers to ensure design implementation quality",
    ],
    requirements: [
      "2+ years of experience in UI/UX design",
      "Proficiency in Figma or similar design tools",
      "Strong portfolio showcasing web and mobile designs",
      "Understanding of design systems and accessibility",
      "Excellent visual design skills and attention to detail",
    ],
    benefits: [
      "Competitive salary",
      "Hybrid work model",
      "Design tool subscriptions",
      "Health insurance",
      "Career growth opportunities",
    ],
    isRemote: false,
    postedDate: "2026-01-22",
  },
  {
    id: "frontend-intern",
    title: "Frontend Developer Intern",
    department: "Engineering",
    location: "Lagos, Nigeria",
    type: "internship",
    experience: "0-1 years",
    description:
      "Great opportunity for aspiring developers! Join our team as an intern and learn from experienced engineers while working on real projects.",
    responsibilities: [
      "Learn and apply modern frontend development practices",
      "Work on real projects under mentorship",
      "Participate in code reviews and team meetings",
      "Contribute to documentation and testing",
      "Present your work and learnings to the team",
    ],
    requirements: [
      "Currently pursuing or recently completed a degree in CS or related field",
      "Basic understanding of HTML, CSS, and JavaScript",
      "Familiarity with React is a plus",
      "Eagerness to learn and grow",
      "Good communication skills",
    ],
    benefits: [
      "Competitive stipend",
      "Mentorship from senior engineers",
      "Real-world project experience",
      "Potential for full-time offer",
      "Flexible hours for students",
    ],
    salary: "₦100,000 - ₦150,000/month",
    isRemote: false,
    postedDate: "2026-01-24",
  },
];
