# Generated by Django 5.2.10 on 2026-05-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
