# Generated by Django 5.2.10 on 2026-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_portfolio_category_remove_portfolio_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, default='website', help_text='Where the message originated from (e.g., portfolio, main app)', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
